In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/survey_results_public.csv', index_col='Respondent')

In [3]:
df.tail(10)

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
64104,NaN,Yes,NaN,19,NaN,NaN,NaN,Poland,NaN,NaN,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,2,NaN
64236,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64330,NaN,Yes,NaN,5,NaN,NaN,NaN,Thailand,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
64480,NaN,Yes,NaN,21,NaN,NaN,NaN,Morocco,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Just as welcome now as I felt last year,NaN,3,NaN
64567,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Netherlands,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,ASP.NET Core,NaN,NaN,NaN,NaN
64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64898,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Viet Nam,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64925,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NaN,...,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [4]:
df.shape

(64461, 60)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 64461 entries, 1 to 65112
Data columns (total 60 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   MainBranch                    64162 non-null  object
 1   Hobbyist                      64416 non-null  object
 2   Age                           45446 non-null  float64
 3   Age1stCode                    57900 non-null  object
 4   CompFreq                      40069 non-null  object
 5   CompTotal                     34826 non-null  float64
 6   ConvertedComp                 34756 non-null  float64
 7   Country                       64072 non-null  object
 8   CurrencyDesc                  45472 non-null  object
 9   CurrencySymbol                45472 non-null  object
 10  DatabaseDesireNextYear        44070 non-null  object
 11  DatabaseWorkedWith            49537 non-null  object
 12  DevType                       49370 non-null  object
 13  EdLevel                       57431 non-null  object
 14  Employment                    63854 non-null  object
 15  Ethnicity                     45948 non-null  object
 16  Gender                        50557 non-null  object
 17  JobFactors                    49349 non-null  object
 18  JobSat                        45194 non-null  object
 19  JobSeek                       51727 non-null  object
 20  LanguageDesireNextYear        54113 non-null  object
 21  LanguageWorkedWith            57378 non-null  object
 22  MiscTechDesireNextYear        42379 non-null  object
 23  MiscTechWorkedWith            40314 non-null  object
 24  NEWCollabToolsDesireNextYear  47287 non-null  object
 25  NEWCollabToolsWorkedWith      52883 non-null  object
 26  NEWDevOps                     42686 non-null  object
 27  NEWDevOpsImpt                 41732 non-null  object
 28  NEWEdImpt                     48465 non-null  object
 29  NEWJobHunt                    42286 non-null  object
 30  NEWJobHuntResearch            41022 non-null  object
 31  NEWLearn                      56156 non-null  object
 32  NEWOffTopic                   50804 non-null  object
 33  NEWOnboardGood                42623 non-null  object
 34  NEWOtherComms                 57205 non-null  object
 35  NEWOvertime                   43231 non-null  object
 36  NEWPurchaseResearch           37321 non-null  object
 37  NEWPurpleLink                 54803 non-null  object
 38  NEWSOSites                    58275 non-null  object
 39  NEWStuck                      54983 non-null  object
 40  OpSys                         56228 non-null  object
 41  OrgSize                       44334 non-null  object
 42  PlatformDesireNextYear        50605 non-null  object
 43  PlatformWorkedWith            53843 non-null  object
 44  PurchaseWhat                  39364 non-null  object
 45  Sexuality                     43992 non-null  object
 46  SOAccount                     56805 non-null  object
 47  SOComm                        56476 non-null  object
 48  SOPartFreq                    46792 non-null  object
 49  SOVisitFreq                   56970 non-null  object
 50  SurveyEase                    51802 non-null  object
 51  SurveyLength                  51701 non-null  object
 52  Trans                         49345 non-null  object
 53  UndergradMajor                50995 non-null  object
 54  WebframeDesireNextYear        40024 non-null  object
 55  WebframeWorkedWith            42279 non-null  object
 56  WelcomeChange                 52683 non-null  object
 57  WorkWeekHrs                   41151 non-null  float64
 58  YearsCode                     57684 non-null  object
 59  YearsCodePro                  46349 non-null  object
dtypes: float64(4), object(56)
memory usage: 16.2+ MB

In [6]:
pd.set_option('display.max_columns', 61)
pd.set_option('display.max_rows', 61)

In [7]:
df

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,NaN,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Not at all important/not necessary,Curious about other opportunities;Wanting to w...,NaN,Once a year,Not sure,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Linux-based,20 to 99 employees,NaN,NaN,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,NaN,NaN,NaN,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Ansible;Chef,Ansible,"Github;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Google Suite (Doc...,NaN,NaN,Very important,NaN,NaN,Once a year,No,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,NaN,NaN,Senior executive/VP,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Very important,NaN,NaN,Once a decade,NaN,NaN,NaN,NaN,Start a free trial,Amused,Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend,Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NaN,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,Cassandra;Couchbase;DynamoDB;Elasticsearch;Fir...,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,Assembly;Bash/Shell/PowerShell;C;C#;C++;Dart;G...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64898,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Viet Nam,NaN,NaN,NaN,NaN,NaN,Primary/elementary school,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64925,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NaN,DynamoDB;Elasticsearch;MongoDB;MySQL;PostgreSQL,Oracle,NaN,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript,HTML/CSS,Node.js,NaN,Github;Gitlab,Confluence;Jira;Slack;Microsoft Teams,NaN,NaN,NaN,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial,"Hello, old friend",Stack Overflow (public Q&A for anyone who codes),Call a coworker or friend;Visit Stack Overflow,Windows,NaN,NaN,Linux;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,NaN,MariaDB;Microsoft SQL Server,MariaDB;Microsoft SQL Server;MySQL;Oracle,NaN,"Other doctoral degree (Ph.D., Ed.D., etc.)",Employed full-time,NaN,NaN,NaN,NaN,NaN,C#;HTML/CSS;Java;JavaScript;SQL,C#;HTML/CSS;Java;JavaScript;SQL,.NET Core;Xamarin,.NET;.NET Core,Github;Microsoft Teams,Github,NaN,NaN,Critically important,NaN,NaN,Once a year,NaN,NaN,NaN,NaN,Start a free trial;Ask developers I know/work ...,Indifferent,NaN,Meditate;Visit Stack Overflow;Go for a walk or...,Windows,NaN,Arduino;Linux;Raspberry Pi;Windows,Android;Arduino;Linux;Raspberry Pi;Windows,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [8]:
schema_df = pd.read_csv('data/survey_results_schema.csv')

In [9]:
schema_df

,Column,QuestionText
0,Respondent,Randomized respondent ID number (not in order ...
1,MainBranch,Which of the following options best describes ...
2,Hobbyist,Do you code as a hobby?
3,Age,What is your age (in years)? If you prefer not...
4,Age1stCode,At what age did you write your first line of c...
5,CompFreq,"Is that compensation weekly, monthly, or yearly?"
6,CompTotal,What is your current total compensation (salar...
7,ConvertedComp,Salary converted to annual USD salaries using ...
8,Country,Where do you live?
9,CurrencyDesc,Which currency do you use day-to-day? If your ...
10,CurrencySymbol,Which currency do you use day-to-day? If your ...
11,DatabaseDesireNextYear,Which database environments have you done exte...
12,DatabaseWorkedWith,Which database environments have you done exte...
13,DevType,Which of the following describe you? Please se...
14,EdLevel,Which of the following best describes the high...
15,Employment,Which of the following best describes your cur...
16,Ethnicity,"Which of the following describe you, if any? P..."
17,Gender,"Which of the following describe you, if any? P..."
18,JobFactors,Imagine that you are deciding between two job ...
19,JobSat,How satisfied are you with your current job? (...
20,JobSeek,Which of the following best describes your cur...
21,LanguageDesireNextYear,"Which programming, scripting, and markup langu..."
22,LanguageWorkedWith,"Which programming, scripting, and markup langu..."
23,MiscTechDesireNextYear,"Which other frameworks, libraries, and tools h..."
24,MiscTechWorkedWith,"Which other frameworks, libraries, and tools h..."
25,NEWCollabToolsDesireNextYear,Which collaboration tools have you done extens...
26,NEWCollabToolsWorkedWith,Which collaboration tools have you done extens...
27,NEWDevOps,Does your company have a dedicated DevOps person?
28,NEWDevOpsImpt,How important is the practice of DevOps to sca...
29,NEWEdImpt,"How important is a formal education, such as a..."
30,NEWJobHunt,"In general, what drives you to look for a new ..."
31,NEWJobHuntResearch,"When job searching, how do you learn more abou..."
32,NEWLearn,How frequently do you learn a new language or ...
33,NEWOffTopic,Do you think Stack Overflow should relax restr...
34,NEWOnboardGood,Do you think your company has a good onboardin...
35,NEWOtherComms,Are you a member of any other online developer...
36,NEWOvertime,How often do you work overtime or beyond the f...
37,NEWPurchaseResearch,"When buying a new tool or software, how do you..."
38,NEWPurpleLink,You search for a coding solution online and th...
39,NEWSOSites,Which of the following Stack Overflow sites ha...
40,NEWStuck,What do you do when you get stuck on a problem...
41,OpSys,What is the primary operating system in which ...
42,OrgSize,Approximately how many people are employed by ...
43,PlatformDesireNextYear,Which platforms have you done extensive develo...
44,PlatformWorkedWith,Which platforms have you done extensive develo...
45,PurchaseWhat,"What level of influence do you, personally, ha..."
46,Sexuality,"Which of the following describe you, if any? P..."
47,SOAccount,Do you have a Stack Overflow account?
48,SOComm,Do you consider yourself a member of the Stack...
49,SOPartFreq,How frequently would you say you participate i...
50,SOVisitFreq,How frequently would you say you visit Stack O...
51,SurveyEase,How easy or difficult was this survey to compl...
52,SurveyLength,How do you feel about the length of the survey...
53,Trans,Are you transgender?
54,UndergradMajor,What was your primary field of study?
55,WebframeDesireNextYear,Which web frameworks have you done extensive d...
56,WebframeWorkedWith,Which web frameworks have you done extensive d...
57,WelcomeChange,"Compared to last year, how welcome do you feel..."
58,WorkWeekHrs,"On average, how many hours per week do you wor..."
59,YearsCode,"Including any education, how many years have y..."
60,YearsCodePro,"NOT including education, how many years have y..."

In [10]:
schema_df.head()

       Column                                       QuestionText
0  Respondent  Randomized respondent ID number (not in order ...
1  MainBranch  Which of the following options best describes ...
2    Hobbyist                            Do you code as a hobby?
3         Age  What is your age (in years)? If you prefer not...
4  Age1stCode  At what age did you write your first line of c...

In [11]:
contacts = {
    'Name': ['Alex', 'India', 'Eric'],
    'Last_Name': ['Clifford', 'Acklin', 'Clifford'],
    'PhoneNumber': [9014409678, 5645454654, 4984566544],
    'Address': ['Harbert', 'Washington', 'Eden'],
}

print(contacts['Name'])

['Alex', 'India', 'Eric']

In [12]:
contacts_df = pd.DataFrame(contacts)
contacts_df

    Name Last_Name  PhoneNumber     Address
0   Alex  Clifford   9014409678     Harbert
1  India    Acklin   5645454654  Washington
2   Eric  Clifford   4984566544        Eden

In [13]:
contacts_name_series = contacts_df['Name']
contacts_name_series

0     Alex
1    India
2     Eric
Name: Name, dtype: object

In [14]:
contacts_df.Name

0     Alex
1    India
2     Eric
Name: Name, dtype: object

In [15]:
contacts_df[['Name', 'Address']]

    Name     Address
0   Alex     Harbert
1  India  Washington
2   Eric        Eden

In [16]:
contacts_df.loc[0:2, ['Name', 'Address']]

    Name     Address
0   Alex     Harbert
1  India  Washington
2   Eric        Eden

In [17]:
contacts_df.iloc[[2], [1]]

  Last_Name
2  Clifford

In [18]:
contacts_df[['Name', 'Address']].iloc[0]

Name          Alex
Address    Harbert
Name: 0, dtype: object

In [19]:
contacts_df.count()

Name           3
Last_Name      3
PhoneNumber    3
Address        3
dtype: int64

In [20]:
contacts_df

    Name Last_Name  PhoneNumber     Address
0   Alex  Clifford   9014409678     Harbert
1  India    Acklin   5645454654  Washington
2   Eric  Clifford   4984566544        Eden

In [21]:
contacts_df.loc[[0, 1], ['Name', 'PhoneNumber']]

    Name  PhoneNumber
0   Alex   9014409678
1  India   5645454654

In [22]:
df.head()

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,DatabaseDesireNextYear,DatabaseWorkedWith,DevType,EdLevel,Employment,Ethnicity,Gender,JobFactors,JobSat,JobSeek,LanguageDesireNextYear,LanguageWorkedWith,MiscTechDesireNextYear,MiscTechWorkedWith,NEWCollabToolsDesireNextYear,NEWCollabToolsWorkedWith,NEWDevOps,NEWDevOpsImpt,NEWEdImpt,NEWJobHunt,NEWJobHuntResearch,NEWLearn,NEWOffTopic,NEWOnboardGood,NEWOtherComms,NEWOvertime,NEWPurchaseResearch,NEWPurpleLink,NEWSOSites,NEWStuck,OpSys,OrgSize,PlatformDesireNextYear,PlatformWorkedWith,PurchaseWhat,Sexuality,SOAccount,SOComm,SOPartFreq,SOVisitFreq,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,Microsoft SQL Server,Elasticsearch;Microsoft SQL Server;Oracle,"Developer, desktop or enterprise applications;...","Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",White or of European descent,Man,"Languages, frameworks, and other technologies ...",Slightly satisfied,I am not interested in new job opportunities,C#;HTML/CSS;JavaScript,C#;HTML/CSS;JavaScript,.NET Core;Xamarin,.NET;.NET Core,Microsoft Teams;Microsoft Azure;Trello,Confluence;Jira;Slack;Microsoft Azure;Trello,No,Somewhat important,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,Often: 1-2 days per week or more,Start a free trial;Ask developers I know/work ...,Amused,Stack Overflow (public Q&A for anyone who codes),Visit Stack Overflow;Go for a walk or other ph...,Windows,2 to 9 employees,Android;iOS;Kubernetes;Microsoft Azure;Windows,Windows,NaN,Straight / Heterosexual,No,"No, not at all",NaN,Multiple times per day,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,NaN,NaN,"Developer, full-stack;Developer, mobile","Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,NaN,NaN,NaN,Very dissatisfied,I am not interested in new job opportunities,Python;Swift,JavaScript;Swift,React Native;TensorFlow;Unity 3D,React Native,Github;Slack,Confluence;Jira;Github;Gitlab;Slack,NaN,NaN,Fairly important,NaN,NaN,Once a year,Not sure,NaN,No,NaN,NaN,Amused,Stack Overflow (public Q&A for anyone who code...,Visit Stack Overflow;Go for a walk or other ph...,MacOS,"1,000 to 4,999 employees",iOS;Kubernetes;Linux;MacOS,iOS,I have little or no influence,NaN,Yes,"Yes, definitely",Less than once per month or monthly,Multiple times per day,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Objective-C;Python;Swift,Objective-C;Python;Swift,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Once a decade,NaN,NaN,No,NaN,NaN,NaN,Stack Overflow (public Q&A for anyone who codes),NaN,Linux-based,NaN,NaN,NaN,NaN,NaN,Yes,"Yes, somewhat",A few times per month or weekly,Daily or almost daily,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,NaN,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",NaN,White or of European descent,Man,Flex time or a flexible schedule;Office enviro...,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Not at all important/not necessary,Curious about other opportunities;Wanting to w...,NaN,Once a year,Not sure,Yes,Yes,Occasionally: 1-2 days per quarter but less th...,NaN,NaN,Stack Overflow (public Q&A for anyone who code...,NaN,Linux-based,20 to 99 employees,NaN,NaN,I have a great deal of influence,Straight / Heterosexual,Yes,"Yes, definitely",A few times per month or weekly,Multiple times per day,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,MySQL;PostgreSQL,MySQL;PostgreSQL;Redis;SQLite,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed full-time,White or of European descent,Man,NaN,NaN,NaN,Java;Ruby;Scala,HTML/CSS;Ruby;SQL,Ansible;Chef,Ansible,"Github;Google Suite (Docs, Meet, etc)",Confluence;Jira;Github;Slack;Google Suite (Doc...,NaN,NaN,Very important,NaN,NaN,Once a year,No,NaN,Yes,NaN,Start a free trial;Ask developers I know/work ...,"Hello, old friend",Stack Overflow (public Q&A for anyone who code...,Call a coworker or friend;Visit Stack Overflow...,Windows,NaN,Docker;Google Cloud Platform;Heroku;Linux;Windows,AWS;Docker;Linux;MacOS;Windows,NaN,Straight / Heterosexual,Yes,"Yes, somewhat",Less than once per month or monthly,A few times per month or weekly,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8

In [23]:
df['Hobbyist'].value_counts()

Yes    50388
No     14028
Name: Hobbyist, dtype: int64

In [24]:
df.shape

(64461, 60)

In [25]:
df.loc[1:5, 'Hobbyist':'Age1stCode']

           Hobbyist   Age Age1stCode
Respondent
1               Yes   NaN         13
2                No   NaN         19
3               Yes   NaN         15
4               Yes  25.0         18
5               Yes  31.0         16

In [26]:
contacts_df.set_index('Name', inplace=True)

In [27]:
contacts_df.index

Index(['Alex', 'India', 'Eric'], dtype='object', name='Name')

In [28]:
contacts_df

      Last_Name  PhoneNumber     Address
Name
Alex   Clifford   9014409678     Harbert
India    Acklin   5645454654  Washington
Eric   Clifford   4984566544        Eden

In [29]:
contacts_df.loc['Alex', 'PhoneNumber']

9014409678

In [30]:
contacts_df.reset_index(inplace=True)
contacts_df

    Name Last_Name  PhoneNumber     Address
0   Alex  Clifford   9014409678     Harbert
1  India    Acklin   5645454654  Washington
2   Eric  Clifford   4984566544        Eden

In [32]:
schema_df.

,Column,QuestionText
0,Respondent,Randomized respondent ID number (not in order ...
1,MainBranch,Which of the following options best describes ...
2,Hobbyist,Do you code as a hobby?
3,Age,What is your age (in years)? If you prefer not...
4,Age1stCode,At what age did you write your first line of c...
5,CompFreq,"Is that compensation weekly, monthly, or yearly?"
6,CompTotal,What is your current total compensation (salar...
7,ConvertedComp,Salary converted to annual USD salaries using ...
8,Country,Where do you live?
9,CurrencyDesc,Which currency do you use day-to-day? If your ...
10,CurrencySymbol,Which currency do you use day-to-day? If your ...
11,DatabaseDesireNextYear,Which database environments have you done exte...
12,DatabaseWorkedWith,Which database environments have you done exte...
13,DevType,Which of the following describe you? Please se...
14,EdLevel,Which of the following best describes the high...
15,Employment,Which of the following best describes your cur...
16,Ethnicity,"Which of the following describe you, if any? P..."
17,Gender,"Which of the following describe you, if any? P..."
18,JobFactors,Imagine that you are deciding between two job ...
19,JobSat,How satisfied are you with your current job? (...
20,JobSeek,Which of the following best describes your cur...
21,LanguageDesireNextYear,"Which programming, scripting, and markup langu..."
22,LanguageWorkedWith,"Which programming, scripting, and markup langu..."
23,MiscTechDesireNextYear,"Which other frameworks, libraries, and tools h..."
24,MiscTechWorkedWith,"Which other frameworks, libraries, and tools h..."
25,NEWCollabToolsDesireNextYear,Which collaboration tools have you done extens...
26,NEWCollabToolsWorkedWith,Which collaboration tools have you done extens...
27,NEWDevOps,Does your company have a dedicated DevOps person?
28,NEWDevOpsImpt,How important is the practice of DevOps to sca...
29,NEWEdImpt,"How important is a formal education, such as a..."
30,NEWJobHunt,"In general, what drives you to look for a new ..."
31,NEWJobHuntResearch,"When job searching, how do you learn more abou..."
32,NEWLearn,How frequently do you learn a new language or ...
33,NEWOffTopic,Do you think Stack Overflow should relax restr...
34,NEWOnboardGood,Do you think your company has a good onboardin...
35,NEWOtherComms,Are you a member of any other online developer...
36,NEWOvertime,How often do you work overtime or beyond the f...
37,NEWPurchaseResearch,"When buying a new tool or software, how do you..."
38,NEWPurpleLink,You search for a coding solution online and th...
39,NEWSOSites,Which of the following Stack Overflow sites ha...
40,NEWStuck,What do you do when you get stuck on a problem...
41,OpSys,What is the primary operating system in which ...
42,OrgSize,Approximately how many people are employed by ...
43,PlatformDesireNextYear,Which platforms have you done extensive develo...
44,PlatformWorkedWith,Which platforms have you done extensive develo...
45,PurchaseWhat,"What level of influence do you, personally, ha..."
46,Sexuality,"Which of the following describe you, if any? P..."
47,SOAccount,Do you have a Stack Overflow account?
48,SOComm,Do you consider yourself a member of the Stack...
49,SOPartFreq,How frequently would you say you participate i...
50,SOVisitFreq,How frequently would you say you visit Stack O...
51,SurveyEase,How easy or difficult was this survey to compl...
52,SurveyLength,How do you feel about the length of the survey...
53,Trans,Are you transgender?
54,UndergradMajor,What was your primary field of study?
55,WebframeDesireNextYear,Which web frameworks have you done extensive d...
56,WebframeWorkedWith,Which web frameworks have you done extensive d...
57,WelcomeChange,"Compared to last year, how welcome do you feel..."
58,WorkWeekHrs,"On average, how many hours per week do you wor..."
59,YearsCode,"Including any education, how many years have y..."
60,YearsCodePro,"NOT including education, how many years have y..."

In [33]:
filt = (contacts_df['Last_Name'] == 'Clifford')

In [40]:
contacts_df[~filt]

    Name Last_Name  PhoneNumber     Address
1  India    Acklin   5645454654  Washington

In [42]:
contacts_df.loc[~(contacts_df['Last_Name'] == 'Clifford'), 'PhoneNumber']
# SELECT phone_number FROM contacts WHERE last_name == "Clifford" AND name == 'Alex';

1    5645454654
Name: PhoneNumber, dtype: int64